ALTER TABLE `games`
ALTER COLUMN 'GameDate' DATETIME,
ALTER COLUMN 'Elab_Date' DATETIME;

ALTER TABLE `members`
ALTER COLUMN 'legacy_updated' DATETIME,
ALTER COLUMN 'legacy_web_updated' DATETIME,
ALTER COLUMN 'renewal_due' DATETIME,
ALTER COLUMN 'join_date' DATETIME,
ALTER COLUMN 'dob' DATETIME;

ALTER TABLE `players`
ALTER COLUMN 'Elab_Date' DATETIME,
ALTER COLUMN 'MExp' DATETIME;

ALTER TABLE `ratings`
ALTER COLUMN 'Elab_Date' DATETIME;

ALTER TABLE `test`
ALTER COLUMN 'entrydate' DATETIME;

ALTER TABLE `tournaments`
ALTER COLUMN 'Tournament_Date' DATETIME,
ALTER COLUMN 'Elab_Date' DATETIME;
