CREATE OR REPLACE VIEW `members_view` AS
    SELECT 
        `m`.`member_id` AS `member_id`,
        `m`.`legacy_updated` AS `legacy_updated`,
        `m`.`legacy_web_updated` AS `legacy_web_updated`,
        `m`.`legacy_new` AS `legacy_new`,
        `m`.`legacy_id` AS `legacy_id`,
        `m`.`legacy_citizen_of` AS `legacy_citizen_of`,
        `m`.`legacy_source` AS `legacy_source`,
        `m`.`full_name` AS `full_name`,
        `m`.`given_names` AS `given_names`,
        `m`.`family_name` AS `family_name`,
        `m`.`renewal_due` AS `renewal_due`,
        `m`.`join_date` AS `join_date`,
        `m`.`dob` AS `dob`,
        `m`.`status` AS `status`,
        `m`.`type` AS `type`,
        `m`.`tags` AS `tags`,
        `m`.`address1` AS `address1`,
        `m`.`address2` AS `address2`,
        `m`.`city` AS `city`,
        `m`.`state` AS `state`,
        `m`.`zip` AS `zip`,
        `m`.`region` AS `region`,
        `m`.`country` AS `country`,
        `m`.`phone` AS `phone`,
        `m`.`phone2` AS `phone2`,
        `m`.`cell` AS `cell`,
        `m`.`email` AS `email`,
        `m`.`email2` AS `email2`,
        `m`.`chapter` AS `chapter`,
        `m`.`chapter_id` AS `chapter_id`,
        `m`.`occupation` AS `occupation`,
        `m`.`citizen` AS `citizen`,
        `m`.`password_plaintext` AS `password_plaintext`,
        `m`.`secret_q` AS `secret_q`,
        `m`.`secret_a` AS `secret_a`,
        `m`.`last_login` AS `last_login`,
        `m`.`reset_token` AS `reset_token`,
        `m`.`reset_token_expires` AS `reset_token_expires`,
        `m`.`password` AS `password`,
        `m`.`notes` AS `notes`,
        `m`.`dues_last_paid` AS `dues_last_paid`,
        `m`.`last_changed` AS `last_changed`,
        `m`.`gender` AS `gender`,
        `m`.`citizen_type` AS `citizen_type`,
        `m`.`non_citizen_country` AS `non_citizen_country`,
        `c`.`display` AS `display`,
        `c`.`size` AS `size`,
        `c`.`contact` AS `contact`,
        `c`.`contact_text` AS `contact_text`,
        `c`.`meeting_text` AS `meeting_text`,
        `c`.`url` AS `url`,
        `c`.`rep_id` AS `rep_id`,
        `p`.`Rating` AS `rating`,
        `p`.`Sigma` AS `sigma`,
        `p`.`Tot_Tournaments` AS `tournaments`,
        `p`.`Tot_Games` AS `games`,
        `p`.`Elab_Date` AS `rating_updated`,
        `t`.`Tournament_Descr` AS `last_tourney`,
        `t`.`Tournament_Date` AS `last_tourney_date`,
        IF(`m`.`dob`,
            ((DATE_FORMAT(NOW(), '%Y') - DATE_FORMAT(`m`.`dob`, '%Y')) - (DATE_FORMAT(NOW(), '00-%m-%d') < DATE_FORMAT(`m`.`dob`, '00-%m-%d'))),
            -(1)) AS `age`
    FROM
        (((`members` `m`
        LEFT JOIN `chapters` `c` ON ((`m`.`member_id` = `c`.`member_id`)))
        LEFT JOIN `players` `p` ON ((`m`.`member_id` = `p`.`Pin_Player`)))
        LEFT JOIN `tournaments` `t` ON ((`p`.`Last_Appearance` = `t`.`Tournament_Code`)));

