ALTER TABLE `ratings`
ADD COLUMN `id` INT NOT NULL AUTO_INCREMENT AFTER `Tournament_Code`,
CHANGE COLUMN `Pin_Player` `Pin_Player` INT(8) UNSIGNED NULL ,
CHANGE COLUMN `Elab_Date` `Elab_Date` DATE NULL,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`),
ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC);
